version: 2.1

orbs:
  cypress: cypress-io/cypress@1.28.0

executors:
  my-cypress-executor:
    docker:
      - image: cypress/browsers:node14.16.0-chrome90-ff88

jobs:
  validate:
    executor: my-cypress-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn validate
  release:
    executor: my-cypress-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn semantic-release

workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          executor: my-cypress-executor
          browser: chrome
          start: yarn serve
          wait-on: '--timeout 120000 http://localhost:8000'
      - validate:
          requires:
            - cypress/run
      - release:
          context:
            - release
          requires:
            - validate
          filters:
            branches:
              only: master
